services:
  nyxguard-manager:
    build:
      context: .
      dockerfile: dev/custom-location-port/Dockerfile
    image: nyxguardmanager:4.0.16-dev-custom-location-port
    environment:
      NPM_BUILD_VERSION: "4.0.16"
      NPM_BUILD_COMMIT: "dev-custom-location-port-integer"
      NPM_BUILD_DATE: "2026-08-30"
