import fs from 'node:fs/promises';
import path from 'node:path';
const assets=path.join(process.argv[2]||'/app','frontend/assets');
function replace(source,before,after){if(source.split(before).length!==2)throw new Error('Task 3 asset contract mismatch');return source.replace(before,after)}
const gateFile=path.join(assets,'index-BiykMfhJ.js'),webFile=path.join(assets,'index-B5xIFQm5.js');
let gate=await fs.readFile(gateFile,'utf8'),web=await fs.readFile(webFile,'utf8');
gate=replace(gate,'if(g.isLoading||!l)return', 'if(g.isError&&!l)return e.jsx(I,{framed:!0,children:e.jsxs("div",{className:a.card,children:[e.jsx("h2",{children:"GlobalGate Security Layer"}),e.jsx("div",{className:a.error,role:"alert",children:"Unable to load GlobalGate settings."}),e.jsx("button",{type:"button",className:a.ghost,onClick:()=>g.refetch(),disabled:g.isFetching,children:"Retry"})]})});if(g.isLoading||!l)return');
web=replace(web,'return e.jsx("div",{className:r.page,children:e.jsx("div",{className:"container-xl nyx-scroll-theme"', 'if(!a.data)return e.jsx("div",{className:r.page,children:e.jsxs("div",{className:r.card,children:[e.jsx("h2",{className:r.title,children:e.jsx(t,{id:"web-controls.title"})}),e.jsx("div",{role:a.isError?"alert":"status",className:a.isError?"alert alert-danger":r.muted,children:a.isError?"Unable to load Web Controls policy.":"Loading Web Controls policy…"}),a.isError&&e.jsx(v,{className:"btn-outline-light",onClick:()=>a.refetch(),disabled:a.isFetching,children:"Retry"})]})});return e.jsx("div",{className:r.page,children:e.jsx("div",{className:"container-xl nyx-scroll-theme"');
web=replace(web,'e.jsxs("div",{className:r.kpiRow,children:', 'g.isError&&e.jsxs("div",{className:"alert alert-danger",role:"alert",children:["Unable to load Web Controls analytics. ",e.jsx(v,{className:"btn-outline-light",onClick:()=>g.refetch(),disabled:g.isFetching,children:"Retry analytics"})]}),e.jsxs("div",{className:r.kpiRow,children:');
for(const category of ['inbound','browser'])web=replace(web,`g.data?.byCategory?.${category}?.toLocaleString?.()??"0"`,`g.isError?"Unavailable":g.isPending?"Loading…":g.data?.byCategory?.${category}?.toLocaleString?.()??"0"`);
web=replace(web,'children:f.data?.items?.length?f.data.items.length:0','children:f.isError?"Unavailable":f.isPending?"Loading…":f.data?.items?.length??0');
web=replace(web,'!f.data?.items?.length&&e.jsx("tr",{children:e.jsx("td",{colSpan:4,className:r.muted,children:e.jsx(t,{id:"web-controls.no-events",data:{window:k.find(s=>s.value===n)?.label??`${n}h`}})})})', '(!f.data?.items?.length||f.isError)&&e.jsx("tr",{children:e.jsx("td",{colSpan:4,className:r.muted,children:f.isError?e.jsxs("div",{role:"alert",children:["Unable to load Web Controls events. ",e.jsx(v,{className:"btn-outline-light",onClick:()=>f.refetch(),disabled:f.isFetching,children:"Retry events"})]}):f.isPending?"Loading Web Controls events…":e.jsx(t,{id:"web-controls.no-events",data:{window:k.find(s=>s.value===n)?.label??`${n}h`}})})})');
await fs.writeFile(gateFile,gate);await fs.writeFile(webFile,web);
